{
  "openapi": "3.0.3",
  "info": {
    "title": "FasaPay Account API",
    "description": "FasaPay Account API",
    "version": "1.0.1"
  },
  "servers": [
    {
      "url": "https://api.fasapay.co.id",
      "description": "Live Server"
    },
    {
      "url": "https://sandbox.fasapay.id/api",
      "description": "Sandbox Server"
    },
    {
      "url": "https://api.test.fasapay.id",
      "description": "TEST Server"
    }
  ],
  "security": [
    {
      "oAuth": []
    }
  ],
  "paths": {
    "/fasafasa": {
      "post": {
        "summary": "Transfer Fasa Cash to Another User. Only Available to ACTIVE User",
        "operationId": "transferFasaFasa",
        "security": [
          {
            "oAuth": [
              "transfer"
            ]
          }
        ]
      }
    },
    "/my/account": {
      "get": {
        "summary": "Get Account Data",
        "operationId": "getMyAccount",
        "security": [
          {
            "oAuth": []
          }
        ]
      }
    },
    "/wallet": {
      "get": {
        "summary": "Get Available Wallet",
        "operationId": "getMyWallet",
        "security": [
          {
            "oAuth": [
              "finance"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "Get Available Wallet",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Wallet"
                  }
                }
              }
            },
            "links": {
              "GetWalletBalance": {
                "operationId": "getBalance"
              }
            }
          }
        }
      }
    },
    "/wallet/{name}": {
      "get": {
        "summary": "Get Wallet balance",
        "operationId": "getBalance",
        "security": [
          {
            "oAuth": [
              "finance"
            ]
          }
        ]
      }
    },
    "/withdraw": {
      "post": {
        "summary": "Request Withdraw",
        "operationId": "requestWithdraw",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "Withdraw Data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WithdrawData"
                }
              }
            },
            "links": {
              "getWithdrawDetailByBatchnumber": {
                "operationId": "getWithdrawDetail",
                "description": "The `batchnumber` returned in the response can be used as the `batchnumber` parameter in `GET /withdraw/{batchnumber}`\n"
              }
            }
          },
          "400": {
            "description": "Input Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/withdraw/{batchnumber}": {
      "get": {
        "summary": "Get Withdraw Detail by Batchnumber",
        "operationId": "getWithdrawDetail"
      }
    },
    "/withdraw/bank-dst": {
      "get": {
        "summary": "Get List of Available Bank Destination",
        "operationId": "getWithdrawBankDst",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      }
    },
    "/bank": {
      "post": {
        "summary": "Create New Bank Destination",
        "operationId": "createBank",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "The Detail ID and Detail of the New Bank",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Bank"
                }
              }
            },
            "links": {
              "getBankbyId": {
                "operationId": "getBank",
                "description": "The `id` returned in the response can be used as the `idBank` parameter in `GET /bank/{idBank}`\n"
              },
              "deleteBankById": {
                "operationId": "deleteBank",
                "description": "The `id` returned in the response can be used as the `idBank` parameter in `DELETE /bank/{idBank}`\n"
              },
              "updateBankById": {
                "operationId": "updateBank",
                "description": "The `id` returned in the response can be used as the `idBank` parameter in `PUT /bank/{idBank}`\n"
              }
            }
          }
        }
      },
      "get": {
        "summary": "Get List of Registered Bank Destination",
        "operationId": "getBanks",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      }
    },
    "/bank/{idBank}": {
      "delete": {
        "summary": "Delete Bank",
        "operationId": "deleteBank",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get Bank Data",
        "operationId": "getBank",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Bank Data",
        "operationId": "updateBank",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      }
    },
    "/bank-bank": {
      "post": {
        "summary": "Request Bank to Bank Transfer",
        "operationId": "requestBankBank",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ],
        "responses": {
          "200": {
            "description": "Bank to Bank Transfer Request Accepted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BankBankData"
                }
              }
            },
            "links": {
              "getBankBankDetailByBatchnumber": {
                "operationId": "getBankBankDetail",
                "description": "The `batchnumber` returned in the response can be used as the `batchnumber` parameter in `GET /bank-bank/{batchnumber}`\n"
              }
            }
          }
        }
      }
    },
    "/bank-bank/{batchnumber}": {
      "get": {
        "summary": "Get Bank Bank Detail by Batchnumber",
        "operationId": "getBankBankDetail"
      }
    },
    "/bank-bank/bank-dst": {
      "get": {
        "summary": "Get List of Available Bank Destination",
        "operationId": "getBankBankBankDst",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      }
    },
    "/bank-bank/bank-src": {
      "get": {
        "summary": "Get List of Available Bank Source",
        "operationId": "getBankBankBankSrc",
        "security": [
          {
            "oAuth": [
              "withdraw"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oAuth": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/auth/token",
            "scopes": {
              "transfer": "Create Topup, Transfer, Payment",
              "withdraw": "Create Withdraw, Fasa to Bank,\nCreate and Modify Bank Account,\nBank to Bank Transfer\n",
              "finance": "Read Transaction History, Account Balance"
            }
          }
        }
      }
    }
  }
}